apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: candig
  labels:
    app: keycloak
data:
  KC_LOG_LEVEL: "DEBUG"
  KC_METRICS_ENABLED: "true"
  KC_HEALTH_ENABLED: "true"
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME_STRICT_HTTPS: "false"
  KC_HTTP_ENABLED: "true"
  KC_PROXY: "edge"
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  labels:
    app: keycloak
