apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: candig
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: managed-csi
  resources:
    requests:
      storage: 100Gi
