apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: candig
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: managed-csi
  resources:
    requests:
      storage: 50Gi
