apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  selector: { app: postgres }
  ports:
    - name: tcp
      port: 5432
      targetPort: 5432
  type: ClusterIP
