apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: candig
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      initContainers:
        - name: keycloak-setup
          image: busybox
          command: ["sh", "/setup/keycloak_setup.sh"]
          env:
            - name: DEFAULT_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-password
                  key: KEYCLOAK_ADMIN
          volumeMounts:
            - name: setup-scripts
              mountPath: /setup
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.2
          args: ["start"]
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: KC_DB_URL
                  optional: true
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: POSTGRES_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: POSTGRES_PASSWORD
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-password
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-password
                  key: KEYCLOAK_ADMIN_PASSWORD
          envFrom:
            - configMapRef:
                name: keycloak-config
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/keycloak/data
      volumes:
        - name: setup-scripts
          configMap:
            name: keycloak-setup-scripts
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-data
