apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: candig
spec:
  serviceName: minio
  replicas: 1
  selector:
    matchLabels: { app: minio }
  template:
    metadata:
      labels: { app: minio }
    spec:
      initContainers:
        - name: secret-generator
          image: busybox
          command: ["sh", "-c", "echo Generating minio secrets; sleep 5"]
          env:
            - name: SECRET_NAME
              value: minio-credentials
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          args: ["server", "/data"]
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef: { name: minio-credentials, key: MINIO_ROOT_USER }
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef: { name: minio-credentials, key: MINIO_ROOT_PASSWORD }
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: managed-csi
        resources:
          requests:
            storage: 100Gi
