apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: candig
spec:
  serviceName: vault
  replicas: 1
  selector:
    matchLabels: { app: vault }
  template:
    metadata:
      labels: { app: vault }
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:1.17
          args: ["server", "-dev"]  # TODO: replace with HA/raft config for prod
          ports:
            - containerPort: 8200
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: dev-root-token  # TODO: remove for prod
          volumeMounts:
            - name: data
              mountPath: /vault/file
  volumeClaimTemplates:
    - metadata: { name: data }
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: managed-csi
        resources:
          requests: { storage: 10Gi }
